# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BrowseTrainingsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 600)
        MainWindow.setAcceptDrops(False)
        MainWindow.setStyleSheet("\n"
"border: 10px solid #FB98AD;background-color: #0C0C0C;\n"
"color: #FB98AD")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.edit_training_btn = QtWidgets.QPushButton(self.centralwidget)
        self.edit_training_btn.setGeometry(QtCore.QRect(120, 490, 151, 71))
        self.edit_training_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.edit_training_btn.setStyleSheet("background-color: #1D1D1D;border: 3px solid #FB98AD;\n"
"font: 8pt \"PRIMETIME\";")
        self.edit_training_btn.setObjectName("edit_training_btn")
        self.delete_training_btn = QtWidgets.QPushButton(self.centralwidget)
        self.delete_training_btn.setGeometry(QtCore.QRect(320, 490, 151, 71))
        self.delete_training_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delete_training_btn.setStyleSheet("background-color: #1D1D1D;border: 3px solid #FB98AD;\n"
"font: 8pt \"PRIMETIME\";")
        self.delete_training_btn.setObjectName("delete_training_btn")
        self.new_training_btn = QtWidgets.QPushButton(self.centralwidget)
        self.new_training_btn.setGeometry(QtCore.QRect(520, 490, 151, 71))
        self.new_training_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.new_training_btn.setStyleSheet("background-color: #1D1D1D;border: 3px solid #FB98AD;\n"
"font: 8pt \"PRIMETIME\";")
        self.new_training_btn.setObjectName("new_training_btn")
        self.ur_train_lbl = QtWidgets.QLabel(self.centralwidget)
        self.ur_train_lbl.setGeometry(QtCore.QRect(120, 20, 321, 41))
        self.ur_train_lbl.setStyleSheet("font: 20pt \"PRIMETIME\";\n"
"border: none;")
        self.ur_train_lbl.setObjectName("ur_train_lbl")
        self.main_menu_btn = QtWidgets.QPushButton(self.centralwidget)
        self.main_menu_btn.setGeometry(QtCore.QRect(20, 20, 81, 41))
        self.main_menu_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.main_menu_btn.setStyleSheet("background-color: #1D1D1D;border: 3px solid #FB98AD;\n"
"font: 8pt \"PRIMETIME\";")
        self.main_menu_btn.setObjectName("main_menu_btn")
        self.refresh_btn = QtWidgets.QPushButton(self.centralwidget)
        self.refresh_btn.setGeometry(QtCore.QRect(690, 20, 81, 41))
        self.refresh_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.refresh_btn.setStyleSheet("background-color: #1D1D1D;border: 3px solid #FB98AD;\n"
"font: 8pt \"PRIMETIME\";")
        self.refresh_btn.setObjectName("refresh_btn")
        self.training_list_collection = QtWidgets.QListWidget(self.centralwidget)
        self.training_list_collection.setGeometry(QtCore.QRect(120, 90, 291, 361))
        self.training_list_collection.setStyleSheet("font: 10pt;")
        self.training_list_collection.setObjectName("training_list_collection")
        self.show_exercise_btn = QtWidgets.QPushButton(self.centralwidget)
        self.show_exercise_btn.setGeometry(QtCore.QRect(530, 20, 141, 41))
        self.show_exercise_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.show_exercise_btn.setStyleSheet("background-color: #1D1D1D;border: 3px solid #FB98AD;\n"
"font: 8pt \"PRIMETIME\";")
        self.show_exercise_btn.setObjectName("show_exercise_btn")
        self.exercises_panel = QtWidgets.QListWidget(self.centralwidget)
        self.exercises_panel.setGeometry(QtCore.QRect(450, 90, 221, 361))
        self.exercises_panel.setStyleSheet("font: 10pt;")
        self.exercises_panel.setObjectName("exercises_panel")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BROWSE TRAININGS"))
        self.edit_training_btn.setText(_translate("MainWindow", "EDIT"))
        self.delete_training_btn.setText(_translate("MainWindow", "DELETE"))
        self.new_training_btn.setText(_translate("MainWindow", "NEW"))
        self.ur_train_lbl.setText(_translate("MainWindow", "YOUR TRAININGS"))
        self.main_menu_btn.setText(_translate("MainWindow", "BACK"))
        self.refresh_btn.setText(_translate("MainWindow", "REFRESH"))
        self.show_exercise_btn.setText(_translate("MainWindow", "SHOW EXERCISES"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
