# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CreateNewTraining.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(790, 600)
        MainWindow.setStyleSheet("\n"
"border: 10px solid #FB98AD;background-color: #0C0C0C;\n"
"color: #FB98AD")
        MainWindow.setProperty("BODYWEIGHT", "")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.choose_type_btn = QtWidgets.QPushButton(self.centralwidget)
        self.choose_type_btn.setGeometry(QtCore.QRect(120, 20, 452, 45))
        self.choose_type_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.choose_type_btn.setStyleSheet("border: none;\n"
"font: 20pt \"PRIMETIME\";")
        self.choose_type_btn.setObjectName("choose_type_btn")
        self.main_menu_btn = QtWidgets.QPushButton(self.centralwidget)
        self.main_menu_btn.setGeometry(QtCore.QRect(20, 20, 81, 41))
        self.main_menu_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.main_menu_btn.setStyleSheet("background-color: #1D1D1D;border: 3px solid #FB98AD;\n"
"font: 8pt \"PRIMETIME\";")
        self.main_menu_btn.setObjectName("main_menu_btn")
        self.bodyweight_btn = QtWidgets.QPushButton(self.centralwidget)
        self.bodyweight_btn.setGeometry(QtCore.QRect(180, 150, 151, 71))
        self.bodyweight_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bodyweight_btn.setStyleSheet("background-color: #1D1D1D;border: 3px solid #FB98AD;\n"
"font: 8pt \"PRIMETIME\";")
        self.bodyweight_btn.setObjectName("bodyweight_btn")
        self.bw_combo = QtWidgets.QComboBox(self.centralwidget)
        self.bw_combo.setGeometry(QtCore.QRect(190, 150, 171, 81))
        self.bw_combo.setStyleSheet("background-color: #1D1D1D;border: 3px solid #FB98AD;\n"
"font: 8pt \"PRIMETIME\";text-align: center;")
        self.bw_combo.setObjectName("bw_combo")
        self.bw_combo.addItem("")
        self.bw_combo.addItem("")
        self.bw_combo.addItem("")
        self.cardio_combo = QtWidgets.QComboBox(self.centralwidget)
        self.cardio_combo.setGeometry(QtCore.QRect(510, 150, 171, 81))
        self.cardio_combo.setStyleSheet("background-color: #1D1D1D;border: 3px solid #FB98AD;\n"
"font: 8pt \"PRIMETIME\";text-align: center;")
        self.cardio_combo.setObjectName("cardio_combo")
        self.cardio_combo.addItem("")
        self.cardio_combo.addItem("")
        self.cardio_combo.addItem("")
        self.wl_combo = QtWidgets.QComboBox(self.centralwidget)
        self.wl_combo.setGeometry(QtCore.QRect(190, 280, 171, 81))
        self.wl_combo.setStyleSheet("background-color: #1D1D1D;border: 3px solid #FB98AD;\n"
"font: 8pt \"PRIMETIME\";text-align: center;")
        self.wl_combo.setObjectName("wl_combo")
        self.wl_combo.addItem("")
        self.wl_combo.addItem("")
        self.wl_combo.addItem("")
        self.mixed_combo = QtWidgets.QComboBox(self.centralwidget)
        self.mixed_combo.setGeometry(QtCore.QRect(510, 280, 171, 81))
        self.mixed_combo.setStyleSheet("background-color: #1D1D1D;border: 3px solid #FB98AD;\n"
"font: 8pt \"PRIMETIME\";text-align: center;")
        self.mixed_combo.setObjectName("mixed_combo")
        self.mixed_combo.addItem("")
        self.next_btn = QtWidgets.QPushButton(self.centralwidget)
        self.next_btn.setGeometry(QtCore.QRect(340, 500, 111, 61))
        font = QtGui.QFont()
        font.setFamily("PRIMETIME")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.next_btn.setFont(font)
        self.next_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.next_btn.setStyleSheet("background-color: #1D1D1D;border: 3px solid #FB98AD;\n"
"font: 12pt \"PRIMETIME\";")
        self.next_btn.setObjectName("next_btn")
        self.chosen_type_label = QtWidgets.QLabel(self.centralwidget)
        self.chosen_type_label.setGeometry(QtCore.QRect(110, 400, 571, 21))
        font = QtGui.QFont()
        font.setFamily("PRIMETIME")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.chosen_type_label.setFont(font)
        self.chosen_type_label.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        self.chosen_type_label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chosen_type_label.setStyleSheet("border: none;\n"
"font: 8pt \"PRIMETIME\";")
        self.chosen_type_label.setText("")
        self.chosen_type_label.setAlignment(QtCore.Qt.AlignCenter)
        self.chosen_type_label.setObjectName("chosen_type_label")
        self.chosen_training_label = QtWidgets.QLabel(self.centralwidget)
        self.chosen_training_label.setGeometry(QtCore.QRect(110, 440, 571, 21))
        font = QtGui.QFont()
        font.setFamily("PRIMETIME")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.chosen_training_label.setFont(font)
        self.chosen_training_label.setStyleSheet("border: none;\n"
"font: 8pt \"PRIMETIME\";")
        self.chosen_training_label.setText("")
        self.chosen_training_label.setAlignment(QtCore.Qt.AlignCenter)
        self.chosen_training_label.setObjectName("chosen_training_label")
        self.bw_btn = QtWidgets.QPushButton(self.centralwidget)
        self.bw_btn.setGeometry(QtCore.QRect(110, 150, 81, 81))
        self.bw_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bw_btn.setStyleSheet("border: none;\n"
"background-color: #FB98AD;")
        self.bw_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/023-muscle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bw_btn.setIcon(icon)
        self.bw_btn.setIconSize(QtCore.QSize(60, 60))
        self.bw_btn.setObjectName("bw_btn")
        self.cardio_btn = QtWidgets.QPushButton(self.centralwidget)
        self.cardio_btn.setGeometry(QtCore.QRect(430, 150, 81, 81))
        self.cardio_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cardio_btn.setStyleSheet("border: none;\n"
"background-color: #FB98AD;")
        self.cardio_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resources/017-heart rate.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cardio_btn.setIcon(icon1)
        self.cardio_btn.setIconSize(QtCore.QSize(60, 60))
        self.cardio_btn.setObjectName("cardio_btn")
        self.wl_btn = QtWidgets.QPushButton(self.centralwidget)
        self.wl_btn.setGeometry(QtCore.QRect(110, 280, 81, 81))
        self.wl_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.wl_btn.setStyleSheet("border: none;\n"
"background-color: #FB98AD;")
        self.wl_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("resources/007-dumbbell.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.wl_btn.setIcon(icon2)
        self.wl_btn.setIconSize(QtCore.QSize(60, 60))
        self.wl_btn.setObjectName("wl_btn")
        self.mixed_btn = QtWidgets.QPushButton(self.centralwidget)
        self.mixed_btn.setGeometry(QtCore.QRect(430, 280, 81, 81))
        self.mixed_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mixed_btn.setStyleSheet("border: none;\n"
"background-color: #FB98AD;")
        self.mixed_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("resources/sport.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mixed_btn.setIcon(icon3)
        self.mixed_btn.setIconSize(QtCore.QSize(60, 60))
        self.mixed_btn.setObjectName("mixed_btn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Create New Training"))
        self.choose_type_btn.setText(_translate("MainWindow", "CHOOSE TRAINING TYPE"))
        self.main_menu_btn.setText(_translate("MainWindow", "BACK"))
        self.bodyweight_btn.setText(_translate("MainWindow", "BODY WEIGHT"))
        self.bw_combo.setItemText(0, _translate("MainWindow", "   BODY WEIGHT"))
        self.bw_combo.setItemText(1, _translate("MainWindow", "   YOGA"))
        self.bw_combo.setItemText(2, _translate("MainWindow", "   CALISTHENICS"))
        self.cardio_combo.setItemText(0, _translate("MainWindow", "   CARDIO"))
        self.cardio_combo.setItemText(1, _translate("MainWindow", "   HIIT"))
        self.cardio_combo.setItemText(2, _translate("MainWindow", "   JOGGING"))
        self.wl_combo.setItemText(0, _translate("MainWindow", "   WEIGHT LIFTING"))
        self.wl_combo.setItemText(1, _translate("MainWindow", "   MACHINES"))
        self.wl_combo.setItemText(2, _translate("MainWindow", "   FREE WEIGHTS"))
        self.mixed_combo.setItemText(0, _translate("MainWindow", "   MIXED"))
        self.next_btn.setText(_translate("MainWindow", "NEXT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
