# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditTrainingWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("\n"
"border: 10px solid #FB98AD;background-color: #0C0C0C;\n"
"color: #FB98AD;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.back_btn = QtWidgets.QPushButton(self.centralwidget)
        self.back_btn.setGeometry(QtCore.QRect(20, 20, 81, 41))
        self.back_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.back_btn.setStyleSheet("background-color: #1D1D1D;border: 3px solid #FB98AD;\n"
"font: 8pt \"PRIMETIME\";")
        self.back_btn.setObjectName("back_btn")
        self.ur_train_lbl = QtWidgets.QLabel(self.centralwidget)
        self.ur_train_lbl.setGeometry(QtCore.QRect(120, 20, 401, 41))
        self.ur_train_lbl.setStyleSheet("font: 20pt \"PRIMETIME\";\n"
"border: none;")
        self.ur_train_lbl.setObjectName("ur_train_lbl")
        self.exercises_panel = QtWidgets.QListWidget(self.centralwidget)
        self.exercises_panel.setGeometry(QtCore.QRect(120, 150, 231, 311))
        self.exercises_panel.setStyleSheet("font: 10pt;")
        self.exercises_panel.setObjectName("exercises_panel")
        self.training_title = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.training_title.setGeometry(QtCore.QRect(120, 100, 231, 61))
        self.training_title.setStyleSheet("font: 12pt \"PRIMETIME\";")
        self.training_title.setObjectName("training_title")
        self.add_exercise_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_exercise_btn.setGeometry(QtCore.QRect(510, 490, 161, 71))
        font = QtGui.QFont()
        font.setFamily("PRIMETIME")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.add_exercise_btn.setFont(font)
        self.add_exercise_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_exercise_btn.setStyleSheet("background-color: #1D1D1D;border: 3px solid #FB98AD;\n"
"font: 8pt \"PRIMETIME\";")
        self.add_exercise_btn.setObjectName("add_exercise_btn")
        self.remove_exercise_btn = QtWidgets.QPushButton(self.centralwidget)
        self.remove_exercise_btn.setGeometry(QtCore.QRect(120, 490, 161, 71))
        font = QtGui.QFont()
        font.setFamily("PRIMETIME")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.remove_exercise_btn.setFont(font)
        self.remove_exercise_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.remove_exercise_btn.setStyleSheet("background-color: #1D1D1D;border: 3px solid #FB98AD;\n"
"font: 8pt \"PRIMETIME\";")
        self.remove_exercise_btn.setObjectName("remove_exercise_btn")
        self.new_ex_combo = QtWidgets.QComboBox(self.centralwidget)
        self.new_ex_combo.setGeometry(QtCore.QRect(450, 190, 201, 31))
        self.new_ex_combo.setStyleSheet("background-color: #1D1D1D;border: 3px solid #FB98AD;\n"
"font: 7pt \"PRIMETIME\";")
        self.new_ex_combo.setObjectName("new_ex_combo")
        self.new_ex_combo.addItem("")
        self.new_ex_combo.addItem("")
        self.new_ex_combo.addItem("")
        self.new_ex_combo.addItem("")
        self.new_ex_combo.addItem("")
        self.new_ex_combo.addItem("")
        self.new_ex_combo.addItem("")
        self.exercise_name = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.exercise_name.setGeometry(QtCore.QRect(450, 150, 201, 31))
        self.exercise_name.setStyleSheet("background-color: #1D1D1D;border: 3px solid #FB98AD;\n"
"font: 7pt \"PRIMETIME\";")
        self.exercise_name.setObjectName("exercise_name")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(400, 90, 291, 31))
        self.label.setStyleSheet("font: 12pt \"PRIMETIME\";\n"
"border: none;")
        self.label.setObjectName("label")
        self.reps_btn = QtWidgets.QPushButton(self.centralwidget)
        self.reps_btn.setGeometry(QtCore.QRect(540, 360, 41, 31))
        self.reps_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reps_btn.setStyleSheet("border: none;\n"
"font: 10pt \"PRIMETIME\";\n"
"text-align: left;\n"
"")
        self.reps_btn.setObjectName("reps_btn")
        self.rep_spin = QtWidgets.QSpinBox(self.centralwidget)
        self.rep_spin.setGeometry(QtCore.QRect(460, 360, 61, 31))
        self.rep_spin.setStyleSheet("border: 1px;\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"")
        self.rep_spin.setObjectName("rep_spin")
        self.sets_btn = QtWidgets.QPushButton(self.centralwidget)
        self.sets_btn.setGeometry(QtCore.QRect(540, 310, 41, 31))
        self.sets_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sets_btn.setStyleSheet("border: none;\n"
"font: 10pt \"PRIMETIME\";\n"
"text-align: left;\n"
"")
        self.sets_btn.setObjectName("sets_btn")
        self.set_spin = QtWidgets.QSpinBox(self.centralwidget)
        self.set_spin.setGeometry(QtCore.QRect(460, 310, 61, 31))
        self.set_spin.setStyleSheet("border: 1px;\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"")
        self.set_spin.setObjectName("set_spin")
        self.reps_btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.reps_btn_2.setGeometry(QtCore.QRect(540, 410, 41, 31))
        self.reps_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reps_btn_2.setStyleSheet("border: none;\n"
"font: 10pt \"PRIMETIME\";\n"
"text-align: left;\n"
"")
        self.reps_btn_2.setObjectName("reps_btn_2")
        self.secs_spin = QtWidgets.QSpinBox(self.centralwidget)
        self.secs_spin.setGeometry(QtCore.QRect(460, 410, 61, 31))
        self.secs_spin.setStyleSheet("border: 1px;\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"")
        self.secs_spin.setObjectName("secs_spin")
        self.sets_btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.sets_btn_2.setGeometry(QtCore.QRect(620, 230, 41, 31))
        self.sets_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sets_btn_2.setStyleSheet("border: none;\n"
"font: 10pt \"PRIMETIME\";\n"
"text-align: left;\n"
"")
        self.sets_btn_2.setObjectName("sets_btn_2")
        self.min_spin = QtWidgets.QSpinBox(self.centralwidget)
        self.min_spin.setGeometry(QtCore.QRect(580, 230, 41, 31))
        self.min_spin.setStyleSheet("border: 1px;\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"")
        self.min_spin.setObjectName("min_spin")
        self.kim_spin = QtWidgets.QSpinBox(self.centralwidget)
        self.kim_spin.setGeometry(QtCore.QRect(580, 270, 41, 31))
        self.kim_spin.setStyleSheet("border: 1px;\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"")
        self.kim_spin.setObjectName("kim_spin")
        self.reps_btn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.reps_btn_3.setGeometry(QtCore.QRect(620, 270, 41, 31))
        self.reps_btn_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reps_btn_3.setStyleSheet("border: none;\n"
"font: 10pt \"PRIMETIME\";\n"
"text-align: left;\n"
"")
        self.reps_btn_3.setObjectName("reps_btn_3")
        self.by_time_btn = QtWidgets.QRadioButton(self.centralwidget)
        self.by_time_btn.setGeometry(QtCore.QRect(450, 230, 121, 31))
        self.by_time_btn.setStyleSheet("background-color: #1D1D1D;border: 3px solid #FB98AD;\n"
"font: 7pt \"PRIMETIME\";")
        self.by_time_btn.setObjectName("by_time_btn")
        self.by_dist_btn = QtWidgets.QRadioButton(self.centralwidget)
        self.by_dist_btn.setGeometry(QtCore.QRect(450, 270, 121, 31))
        self.by_dist_btn.setStyleSheet("background-color: #1D1D1D;border: 3px solid #FB98AD;\n"
"font: 7pt \"PRIMETIME\";")
        self.by_dist_btn.setObjectName("by_dist_btn")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(450, 120, 191, 16))
        self.label_2.setStyleSheet("font: 6pt \"PRIMETIME\";\n"
"border: none;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(430, 120, 241, 341))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.show_exercise_btn = QtWidgets.QPushButton(self.centralwidget)
        self.show_exercise_btn.setGeometry(QtCore.QRect(630, 20, 151, 41))
        self.show_exercise_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.show_exercise_btn.setStyleSheet("background-color: #1D1D1D;border: 3px solid #FB98AD;\n"
"font: 8pt \"PRIMETIME\";")
        self.show_exercise_btn.setObjectName("show_exercise_btn")
        self.label_3.raise_()
        self.back_btn.raise_()
        self.ur_train_lbl.raise_()
        self.exercises_panel.raise_()
        self.training_title.raise_()
        self.add_exercise_btn.raise_()
        self.remove_exercise_btn.raise_()
        self.new_ex_combo.raise_()
        self.exercise_name.raise_()
        self.label.raise_()
        self.reps_btn.raise_()
        self.rep_spin.raise_()
        self.sets_btn.raise_()
        self.set_spin.raise_()
        self.reps_btn_2.raise_()
        self.secs_spin.raise_()
        self.sets_btn_2.raise_()
        self.min_spin.raise_()
        self.kim_spin.raise_()
        self.reps_btn_3.raise_()
        self.by_time_btn.raise_()
        self.by_dist_btn.raise_()
        self.label_2.raise_()
        self.show_exercise_btn.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.back_btn.setText(_translate("MainWindow", "BACK"))
        self.ur_train_lbl.setText(_translate("MainWindow", "EDIT YOUR TRAINING"))
        self.training_title.setPlainText(_translate("MainWindow", "TRAINING NAME"))
        self.add_exercise_btn.setText(_translate("MainWindow", "ADD EXERCISE"))
        self.remove_exercise_btn.setText(_translate("MainWindow", "REMOVE EXERCISE"))
        self.new_ex_combo.setItemText(0, _translate("MainWindow", "CHOOSE EXERCISE TYPE"))
        self.new_ex_combo.setItemText(1, _translate("MainWindow", "CALISTHENICS"))
        self.new_ex_combo.setItemText(2, _translate("MainWindow", "FREE WEIGHTS"))
        self.new_ex_combo.setItemText(3, _translate("MainWindow", "HIIT"))
        self.new_ex_combo.setItemText(4, _translate("MainWindow", "JOGGING"))
        self.new_ex_combo.setItemText(5, _translate("MainWindow", "MACHINES"))
        self.new_ex_combo.setItemText(6, _translate("MainWindow", "YOGA"))
        self.exercise_name.setPlainText(_translate("MainWindow", "TYPE EXERCISE NAME"))
        self.label.setText(_translate("MainWindow", "   CREATE NEW EXERCISE"))
        self.reps_btn.setText(_translate("MainWindow", "reps"))
        self.sets_btn.setText(_translate("MainWindow", "sets"))
        self.reps_btn_2.setText(_translate("MainWindow", "secs"))
        self.sets_btn_2.setText(_translate("MainWindow", "MIN"))
        self.reps_btn_3.setText(_translate("MainWindow", "KM"))
        self.by_time_btn.setText(_translate("MainWindow", "BY TIME"))
        self.by_dist_btn.setText(_translate("MainWindow", "BY DISTANCE"))
        self.label_2.setText(_translate("MainWindow", "  FILL IN APPROPRIATE INFO ONLY"))
        self.show_exercise_btn.setText(_translate("MainWindow", "SHOW EXERCISES"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
