# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(790, 600)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setStyleSheet("\n"
"border: 10px solid #FB98AD;background-color: #0C0C0C;\n"
"color: #FB98AD;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.create_btn = QtWidgets.QPushButton(self.centralwidget)
        self.create_btn.setGeometry(QtCore.QRect(460, 450, 161, 71))
        self.create_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.create_btn.setStyleSheet("background-color: #1D1D1D;border: 3px solid #FB98AD;\n"
"font: 8pt \"PRIMETIME\";\n"
"")
        self.create_btn.setObjectName("create_btn")
        self.browse_btn = QtWidgets.QPushButton(self.centralwidget)
        self.browse_btn.setGeometry(QtCore.QRect(170, 450, 161, 71))
        self.browse_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.browse_btn.setStyleSheet("background-color: #1D1D1D;border: 3px solid #FB98AD;\n"
"font: 8pt \"PRIMETIME\";")
        self.browse_btn.setObjectName("browse_btn")
        self.icon = QtWidgets.QLabel(self.centralwidget)
        self.icon.setGeometry(QtCore.QRect(170, 77, 97, 97))
        self.icon.setAutoFillBackground(False)
        self.icon.setStyleSheet("background-color: #FB98AD;")
        self.icon.setText("")
        self.icon.setPixmap(QtGui.QPixmap("resources/user.svg"))
        self.icon.setScaledContents(True)
        self.icon.setObjectName("icon")
        self.profile_btn = QtWidgets.QPushButton(self.centralwidget)
        self.profile_btn.setGeometry(QtCore.QRect(230, 40, 431, 171))
        self.profile_btn.setStyleSheet("background-color: #1D1D1D;font: 20pt \"PRIMETIME\";\n"
"margin: auto;\n"
"border: 5px solid #FB98AD;")
        self.profile_btn.setObjectName("profile_btn")
        self.label_goal = QtWidgets.QLabel(self.centralwidget)
        self.label_goal.setGeometry(QtCore.QRect(160, 280, 451, 111))
        self.label_goal.setStyleSheet("background-color: #1D1D1D;font: 10pt \"PRIMETIME\";\n"
"border: 5px solid #FB98AD;")
        self.label_goal.setText("")
        self.label_goal.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_goal.setObjectName("label_goal")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(170, 240, 241, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setStyleSheet("border: none;\n"
"font: 16pt \"PRIMETIME\";")
        self.label_2.setObjectName("label_2")
        self.refresh_btn = QtWidgets.QPushButton(self.centralwidget)
        self.refresh_btn.setGeometry(QtCore.QRect(690, 20, 81, 41))
        self.refresh_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.refresh_btn.setStyleSheet("background-color: #1D1D1D;border: 3px solid #FB98AD;\n"
"font: 8pt \"PRIMETIME\";")
        self.refresh_btn.setObjectName("refresh_btn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FITNESS APP"))
        self.create_btn.setText(_translate("MainWindow", "CREATE TRAINING"))
        self.browse_btn.setText(_translate("MainWindow", "BROWSE TRAININGS"))
        self.profile_btn.setText(_translate("MainWindow", "HI, BLINK!"))
        self.label_2.setText(_translate("MainWindow", "YOUR GOAL"))
        self.refresh_btn.setText(_translate("MainWindow", "REFRESH"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
