# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NewHiitTraining.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("border: 10px solid #FB98AD;background-color: #0C0C0C;\n"
"color: #FB98AD;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.choose_type_btn = QtWidgets.QPushButton(self.centralwidget)
        self.choose_type_btn.setGeometry(QtCore.QRect(150, 30, 501, 45))
        self.choose_type_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.choose_type_btn.setStyleSheet("border: none;\n"
"font: 20pt \"PRIMETIME\";")
        self.choose_type_btn.setObjectName("choose_type_btn")
        self.exercise_combo = QtWidgets.QComboBox(self.centralwidget)
        self.exercise_combo.setGeometry(QtCore.QRect(200, 120, 171, 81))
        self.exercise_combo.setAcceptDrops(False)
        self.exercise_combo.setStyleSheet("background-color: #1D1D1D;border: 3px solid #FB98AD;\n"
"font: 8pt \"PRIMETIME\";text-align: center;")
        self.exercise_combo.setObjectName("exercise_combo")
        self.exercise_combo.addItem("")
        self.exercise_combo.addItem("")
        self.exercise_combo.addItem("")
        self.exercise_combo.addItem("")
        self.add_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_btn.setGeometry(QtCore.QRect(540, 130, 111, 61))
        font = QtGui.QFont()
        font.setFamily("PRIMETIME")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.add_btn.setFont(font)
        self.add_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_btn.setStyleSheet("background-color: #1D1D1D;border: 3px solid #FB98AD;\n"
"font: 12pt \"PRIMETIME\";")
        self.add_btn.setObjectName("add_btn")
        self.sets_spin = QtWidgets.QSpinBox(self.centralwidget)
        self.sets_spin.setGeometry(QtCore.QRect(400, 120, 61, 31))
        self.sets_spin.setStyleSheet("border: 1px;\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"")
        self.sets_spin.setObjectName("sets_spin")
        self.secs_spin = QtWidgets.QSpinBox(self.centralwidget)
        self.secs_spin.setGeometry(QtCore.QRect(400, 170, 61, 31))
        self.secs_spin.setStyleSheet("border: 1px;\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"")
        self.secs_spin.setObjectName("secs_spin")
        self.sets_btn = QtWidgets.QPushButton(self.centralwidget)
        self.sets_btn.setGeometry(QtCore.QRect(480, 120, 41, 31))
        self.sets_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sets_btn.setStyleSheet("border: none;\n"
"font: 10pt \"PRIMETIME\";\n"
"text-align: left;\n"
"")
        self.sets_btn.setObjectName("sets_btn")
        self.back_btn = QtWidgets.QPushButton(self.centralwidget)
        self.back_btn.setGeometry(QtCore.QRect(20, 20, 81, 41))
        self.back_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.back_btn.setStyleSheet("background-color: #1D1D1D;border: 3px solid #FB98AD;\n"
"font: 8pt \"PRIMETIME\";")
        self.back_btn.setObjectName("back_btn")
        self.remove_training_btn = QtWidgets.QPushButton(self.centralwidget)
        self.remove_training_btn.setGeometry(QtCore.QRect(510, 340, 161, 71))
        font = QtGui.QFont()
        font.setFamily("PRIMETIME")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.remove_training_btn.setFont(font)
        self.remove_training_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.remove_training_btn.setStyleSheet("background-color: #1D1D1D;border: 3px solid #FB98AD;\n"
"font: 8pt \"PRIMETIME\";")
        self.remove_training_btn.setObjectName("remove_training_btn")
        self.training_name = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.training_name.setGeometry(QtCore.QRect(190, 230, 291, 61))
        self.training_name.setStyleSheet("font: 12pt \"PRIMETIME\";")
        self.training_name.setObjectName("training_name")
        self.training_list = QtWidgets.QListWidget(self.centralwidget)
        self.training_list.setGeometry(QtCore.QRect(190, 280, 291, 241))
        self.training_list.setStyleSheet("font: 10pt;")
        self.training_list.setObjectName("training_list")
        self.browse_btn = QtWidgets.QPushButton(self.centralwidget)
        self.browse_btn.setGeometry(QtCore.QRect(510, 440, 161, 71))
        self.browse_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.browse_btn.setStyleSheet("background-color: #1D1D1D;border: 3px solid #FB98AD;\n"
"font: 8pt \"PRIMETIME\";")
        self.browse_btn.setObjectName("browse_btn")
        self.create_training_btn = QtWidgets.QPushButton(self.centralwidget)
        self.create_training_btn.setGeometry(QtCore.QRect(510, 240, 161, 71))
        font = QtGui.QFont()
        font.setFamily("PRIMETIME")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.create_training_btn.setFont(font)
        self.create_training_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.create_training_btn.setStyleSheet("background-color: #1D1D1D;border: 3px solid #FB98AD;\n"
"font: 8pt \"PRIMETIME\";")
        self.create_training_btn.setObjectName("create_training_btn")
        self.sets_btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.sets_btn_2.setGeometry(QtCore.QRect(480, 170, 41, 31))
        self.sets_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sets_btn_2.setStyleSheet("border: none;\n"
"font: 10pt \"PRIMETIME\";\n"
"text-align: left;\n"
"")
        self.sets_btn_2.setObjectName("sets_btn_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.choose_type_btn.setText(_translate("MainWindow", "NEW HIIT TRAINING"))
        self.exercise_combo.setItemText(0, _translate("MainWindow", "CHOOSE EXERCISE"))
        self.exercise_combo.setItemText(1, _translate("MainWindow", "JUMP LUNGE"))
        self.exercise_combo.setItemText(2, _translate("MainWindow", "RUSSIAN TWISTS"))
        self.exercise_combo.setItemText(3, _translate("MainWindow", "MOUNTAIN CLIMBERS"))
        self.add_btn.setText(_translate("MainWindow", "ADD"))
        self.sets_btn.setText(_translate("MainWindow", "sets"))
        self.back_btn.setText(_translate("MainWindow", "BACK"))
        self.remove_training_btn.setText(_translate("MainWindow", "REMOVE EXERCISE"))
        self.training_name.setPlainText(_translate("MainWindow", "Training name"))
        self.browse_btn.setText(_translate("MainWindow", "BROWSE TRAININGS"))
        self.create_training_btn.setText(_translate("MainWindow", " CREATE TRAINING"))
        self.sets_btn_2.setText(_translate("MainWindow", "secs"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
