# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Profile.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(786, 591)
        MainWindow.setStyleSheet("\n"
"border: 10px solid #FB98AD;background-color: #0C0C0C;\n"
"color: #FB98AD")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_menu_btn = QtWidgets.QPushButton(self.centralwidget)
        self.main_menu_btn.setGeometry(QtCore.QRect(20, 20, 81, 41))
        self.main_menu_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.main_menu_btn.setStyleSheet("background-color: #1D1D1D;border: 3px solid #FB98AD;\n"
"font: 8pt \"PRIMETIME\";")
        self.main_menu_btn.setObjectName("main_menu_btn")
        self.choose_type_btn = QtWidgets.QPushButton(self.centralwidget)
        self.choose_type_btn.setGeometry(QtCore.QRect(120, 20, 281, 45))
        self.choose_type_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.choose_type_btn.setStyleSheet("border: none;\n"
"font: 20pt \"PRIMETIME\"; ")
        self.choose_type_btn.setObjectName("choose_type_btn")
        self.browse_btn = QtWidgets.QPushButton(self.centralwidget)
        self.browse_btn.setGeometry(QtCore.QRect(130, 490, 161, 71))
        self.browse_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.browse_btn.setStyleSheet("background-color: #1D1D1D;border: 3px solid #FB98AD;\n"
"font: 8pt \"PRIMETIME\";\n"
"")
        self.browse_btn.setObjectName("browse_btn")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(130, 320, 161, 61))
        self.label_4.setStyleSheet("font: 14pt \"PRIMETIME\";")
        self.label_4.setObjectName("label_4")
        self.age = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.age.setGeometry(QtCore.QRect(320, 160, 311, 61))
        self.age.setObjectName("age")
        self.weight = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.weight.setGeometry(QtCore.QRect(320, 240, 311, 61))
        self.weight.setObjectName("weight")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 160, 161, 61))
        self.label_2.setStyleSheet("font: 14pt \"PRIMETIME\";")
        self.label_2.setObjectName("label_2")
        self.name = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(320, 80, 311, 61))
        self.name.setObjectName("name")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(130, 240, 161, 61))
        self.label_3.setStyleSheet("font: 14pt \"PRIMETIME\";")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(130, 400, 161, 61))
        self.label_5.setStyleSheet("font: 14pt \"PRIMETIME\";")
        self.label_5.setObjectName("label_5")
        self.goal = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.goal.setGeometry(QtCore.QRect(320, 400, 311, 61))
        self.goal.setObjectName("goal")
        self.save_btn = QtWidgets.QPushButton(self.centralwidget)
        self.save_btn.setGeometry(QtCore.QRect(470, 490, 161, 71))
        self.save_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.save_btn.setStyleSheet("background-color: #1D1D1D;border: 3px solid #FB98AD;\n"
"font: 8pt \"PRIMETIME\";\n"
"")
        self.save_btn.setObjectName("save_btn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 80, 161, 61))
        self.label.setStyleSheet("font: 14pt \"PRIMETIME\";")
        self.label.setObjectName("label")
        self.height_btn = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.height_btn.setGeometry(QtCore.QRect(320, 320, 311, 61))
        self.height_btn.setObjectName("height_btn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PROFILE"))
        self.main_menu_btn.setText(_translate("MainWindow", "BACK"))
        self.choose_type_btn.setText(_translate("MainWindow", "YOUR PROFILE"))
        self.browse_btn.setText(_translate("MainWindow", "BROWSE TRAININGS"))
        self.label_4.setText(_translate("MainWindow", "  HEIGHT"))
        self.label_2.setText(_translate("MainWindow", "    AGE"))
        self.label_3.setText(_translate("MainWindow", " WEIGHT"))
        self.label_5.setText(_translate("MainWindow", "   GOAL"))
        self.save_btn.setText(_translate("MainWindow", "SAVE PROFILE"))
        self.label.setText(_translate("MainWindow", "   NAME"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
